import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";

export const metadata = {
  title: "About | Onyitech JournalHub Ltd",
  description: "About Onyitech JournalHub Ltd, its technology focus, services, projects and approach to AI, publishing and workflow automation.",
};

export default function AboutPage() {
  return <><SiteHeader /><main className="detail-page">
    <section className="detail-hero"><div className="wrap"><p className="eyebrow">ABOUT ONYTECH JOURNALHUB</p><h1>Building practical technology where research, publishing and intelligent automation meet.</h1><p className="detail-lede">Onyitech JournalHub Ltd develops software, digital infrastructure and automation for research-driven organizations, academic publishers and teams with real operational problems to solve.</p></div></section>
    <section><div className="wrap two-column"><div><p className="eyebrow">WHO WE ARE</p><h2>A technology company focused on useful digital systems.</h2></div><div><p>Onyitech JournalHub Ltd brings together software engineering, artificial intelligence, machine learning, academic publishing technology and workflow automation.</p><p>Our approach starts with the workflow rather than the technology. We identify the users, information, processes and constraints involved, then design software and infrastructure around the problem.</p><p>Our work is intended for organizations that need dependable digital systems but may have complex research, publishing or operational requirements.</p></div></div></section>
    <section className="audience-section"><div className="wrap"><div className="section-head"><div><p className="eyebrow">OUR TECHNOLOGY FOCUS</p><h2>Four connected areas of engineering.</h2></div></div><div className="services-grid">
      <article className="service-card"><span className="service-number">01</span><h3>AI &amp; Machine Learning</h3><p>AI/ML systems, data pipelines, text intelligence and decision-support components designed around practical use cases.</p></article>
      <article className="service-card"><span className="service-number">02</span><h3>Publishing Technology</h3><p>Open Journal Systems development, journal infrastructure, metadata workflows, DOI-related technical support and digital publishing systems.</p></article>
      <article className="service-card"><span className="service-number">03</span><h3>Workflow Automation</h3><p>Python applications, APIs and automation that connect repetitive processes and help teams manage structured operational workflows.</p></article>
      <article className="service-card"><span className="service-number">04</span><h3>Cloud &amp; Custom Software</h3><p>Application architecture, integrations, databases and cloud infrastructure for organizations with specific technical requirements.</p></article>
    </div></div></section>
    <section><div className="wrap two-column"><div><p className="eyebrow">SELECTED WORK</p><h2>Technology developed around real use cases.</h2></div><div><h3>Ojukwu Journal of Psychological Services</h3><p>We have developed and supported digital publishing infrastructure for the Ojukwu Journal of Psychological Services (OJPS), including its Open Journal Systems platform, publishing workflows and technical support around metadata, DOI and indexing-related processes.</p><p><a className="secondary-link" href="https://psyservicesjournal.org.ng" target="_blank" rel="noreferrer">Visit OJPS →</a> <a className="secondary-link" href="https://ojs.psyservicesjournal.org.ng" target="_blank" rel="noreferrer">Open OJS →</a></p><h3>Pillar AI</h3><p>Pillar AI is an R&amp;D project exploring modular AI/ML architecture, heterogeneous data integration, machine learning pipelines, blockchain intelligence, sentiment signals and automated risk controls.</p><p><a className="secondary-link" href="/rnd">Explore R&amp;D →</a></p></div></div></section>
    <section className="dark-panel"><div className="wrap"><p className="eyebrow">OUR APPROACH</p><h2>Build with clarity, responsibility and maintainability.</h2><p>We aim to build systems that are understandable, maintainable and appropriate to their intended use. We separate experimental research from production claims, document important assumptions and keep human responsibility in workflows where decisions have meaningful consequences.</p><p>Our long-term direction is to combine publishing infrastructure, intelligent automation and cloud-based software into practical tools that can serve research communities and organizations beyond a single project.</p></div></section>
    <section><div className="wrap cta-band"><div><p className="eyebrow">WORK WITH US</p><h2>Have a publishing, automation or AI/ML problem worth building around?</h2></div><a className="btn-primary" href="/contact">Get in touch</a></div></section>
  </main><SiteFooter /></>;
}
